platform:ios,8.0

target ‘ShareDemo’ do

pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKExtension'


pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/WeChat'

end